"""
Instructor Dashboard Schemas

Pydantic v2 schema definitions for all Instructor Dashboard endpoints.
"""

# Dashboard Schemas
from .dashboard_schemas import (
    InstructorDashboardStats,
    UpcomingSessionSummary,
    PendingSubmissionSummary,
    AIFlaggedStudentSummary,
    DashboardOverviewResponse,
)

# Profile Schemas
from .profile_schemas import (
    QualificationSchema,
    SocialLinkSchema,
    PortfolioItemSchema,
    SEOMetaSchema,
    TimeRangeSchema,
    AvailabilityConfigSchema,
    InstructorProfileCreate,
    InstructorProfileUpdate,
    PublicProfileUpdate,
    AvailabilityUpdate,
    PortfolioItemCreate,
    PortfolioItemUpdate,
    OnboardingStepUpdate,
    InstructorProfileResponse,
    PublicInstructorProfileResponse,
)

# Earnings Schemas
from .earnings_schemas import (
    PayoutDetailsSchema,
    InstructorEarningResponse,
    PayoutRequest,
    InstructorPayoutResponse,
    RevenueSplitCreate,
    RevenueSplitUpdate,
    InstructorRevenueSplitResponse,
    CourseEarningsItem,
    SessionEarningsItem,
    EarningsByType,
    EarningsBreakdownResponse,
    EarningsProjectionRequest,
    MonthlyProjection,
    EarningsProjectionResponse,
    RateOptimizationRequest,
    RateOptimizationResponse,
    EarningsQueryParams,
    PayoutQueryParams,
)

# Course Schemas
from .course_schemas import (
    ResourceSchema,
    LessonSchema,
    LessonCreate,
    LessonUpdate,
    CourseCreate,
    CourseUpdate,
    CourseModulesUpdate,
    InstructorCourseResponse,
    CourseAnalyticsResponse,
    AIContentGenerateRequest,
    AIContentGenerateResponse,
    CourseQueryParams,
)

# Assessment Schemas
from .assessment_schemas import (
    AssessmentQuestionSchema,
    QuestionCreate,
    QuestionUpdate,
    AssessmentCreate,
    AssessmentUpdate,
    AssessmentQuestionsUpdate,
    InstructorAssessmentResponse,
    AssessmentSubmissionResponse,
    GradeSubmission,
    BatchGradeRequest,
    AIFeedbackRequest,
    AIFeedbackResponse,
    AIAssessmentGenerateRequest,
    AIAssessmentGenerateResponse,
    RubricCriterion,
    RubricCreate,
    RubricResponse,
    SubmissionQueryParams,
)

# Session Schemas
from .session_schemas import (
    SessionCreate,
    SessionUpdate,
    InstructorSessionResponse,
    SessionStart,
    SessionEnd,
    SessionAttendanceResponse,
    RecordingResponse,
    FollowUpCreate,
    FollowUpUpdate,
    SessionFollowUpResponse,
    AISessionSummaryRequest,
    AISessionSummaryResponse,
    ICEConfigResponse,
    SessionQueryParams,
)

# Insight Schemas
from .insight_schemas import (
    DailyInsightItem,
    InstructorDailyInsightResponse,
    DailyInsightQueryParams,
    CBCCompetencySchema,
    CBCSuggestionSchema,
    CBCAnalysisRequest,
    InstructorCBCAnalysisResponse,
    AIResourceSuggestionsRequest,
    ResourceSuggestion,
    AIResourceSuggestionsResponse,
    ResourceUsageResponse,
)

# Gamification Schemas
from .gamification_schemas import (
    InstructorBadgeResponse,
    InstructorBadgeAwardResponse,
    InstructorPointsResponse,
    PointsLogResponse,
    LeaderboardEntry,
    LeaderboardResponse,
    PeerKudoCreate,
    PeerKudoResponse,
    AchievementProgress,
    GamificationOverviewResponse,
    BadgeQueryParams,
    KudoQueryParams,
)

# Discussion Schemas
from .discussion_schemas import (
    ForumPostCreate,
    ForumPostUpdate,
    InstructorForumPostResponse,
    ForumReplyCreate,
    ForumReplyUpdate,
    InstructorForumReplyResponse,
    ModerationAction,
    SentimentAnalysisResponse,
    ForumPostQueryParams,
    ForumReplyQueryParams,
)

# Security Schemas
from .security_schemas import (
    TOTPSetupResponse,
    TOTPVerifyRequest,
    TOTPEnableRequest,
    TOTPDisableRequest,
    SMSOTPEnableRequest,
    SMSOTPVerifyRequest,
    SMSOTPDisableRequest,
    EmailOTPEnableRequest,
    EmailOTPVerifyRequest,
    EmailOTPDisableRequest,
    TwoFactorStatusResponse,
    BackupCodesRegenerateResponse,
    BackupCodeVerifyRequest,
    LoginHistoryResponse,
    LoginHistoryQueryParams,
    SecurityAlertResponse,
    ActiveSessionResponse,
    RevokeSessionRequest,
    PasswordChangeRequest,
    SecuritySettingsUpdate,
)

__all__ = [
    # Dashboard
    "InstructorDashboardStats",
    "UpcomingSessionSummary",
    "PendingSubmissionSummary",
    "AIFlaggedStudentSummary",
    "DashboardOverviewResponse",
    # Profile
    "QualificationSchema",
    "SocialLinkSchema",
    "PortfolioItemSchema",
    "SEOMetaSchema",
    "TimeRangeSchema",
    "AvailabilityConfigSchema",
    "InstructorProfileCreate",
    "InstructorProfileUpdate",
    "PublicProfileUpdate",
    "AvailabilityUpdate",
    "PortfolioItemCreate",
    "PortfolioItemUpdate",
    "OnboardingStepUpdate",
    "InstructorProfileResponse",
    "PublicInstructorProfileResponse",
    # Earnings
    "PayoutDetailsSchema",
    "InstructorEarningResponse",
    "PayoutRequest",
    "InstructorPayoutResponse",
    "RevenueSplitCreate",
    "RevenueSplitUpdate",
    "InstructorRevenueSplitResponse",
    "CourseEarningsItem",
    "SessionEarningsItem",
    "EarningsByType",
    "EarningsBreakdownResponse",
    "EarningsProjectionRequest",
    "MonthlyProjection",
    "EarningsProjectionResponse",
    "RateOptimizationRequest",
    "RateOptimizationResponse",
    "EarningsQueryParams",
    "PayoutQueryParams",
    # Courses
    "ResourceSchema",
    "LessonSchema",
    "LessonCreate",
    "LessonUpdate",
    "CourseCreate",
    "CourseUpdate",
    "CourseModulesUpdate",
    "InstructorCourseResponse",
    "CourseAnalyticsResponse",
    "AIContentGenerateRequest",
    "AIContentGenerateResponse",
    "CourseQueryParams",
    # Assessments
    "AssessmentQuestionSchema",
    "QuestionCreate",
    "QuestionUpdate",
    "AssessmentCreate",
    "AssessmentUpdate",
    "AssessmentQuestionsUpdate",
    "InstructorAssessmentResponse",
    "AssessmentSubmissionResponse",
    "GradeSubmission",
    "BatchGradeRequest",
    "AIFeedbackRequest",
    "AIFeedbackResponse",
    "AIAssessmentGenerateRequest",
    "AIAssessmentGenerateResponse",
    "RubricCriterion",
    "RubricCreate",
    "RubricResponse",
    "SubmissionQueryParams",
    # Sessions
    "SessionCreate",
    "SessionUpdate",
    "InstructorSessionResponse",
    "SessionStart",
    "SessionEnd",
    "SessionAttendanceResponse",
    "RecordingResponse",
    "FollowUpCreate",
    "FollowUpUpdate",
    "SessionFollowUpResponse",
    "AISessionSummaryRequest",
    "AISessionSummaryResponse",
    "ICEConfigResponse",
    "SessionQueryParams",
    # Insights
    "DailyInsightItem",
    "InstructorDailyInsightResponse",
    "DailyInsightQueryParams",
    "CBCCompetencySchema",
    "CBCSuggestionSchema",
    "CBCAnalysisRequest",
    "InstructorCBCAnalysisResponse",
    "AIResourceSuggestionsRequest",
    "ResourceSuggestion",
    "AIResourceSuggestionsResponse",
    "ResourceUsageResponse",
    # Gamification
    "InstructorBadgeResponse",
    "InstructorBadgeAwardResponse",
    "InstructorPointsResponse",
    "PointsLogResponse",
    "LeaderboardEntry",
    "LeaderboardResponse",
    "PeerKudoCreate",
    "PeerKudoResponse",
    "AchievementProgress",
    "GamificationOverviewResponse",
    "BadgeQueryParams",
    "KudoQueryParams",
    # Discussions
    "ForumPostCreate",
    "ForumPostUpdate",
    "InstructorForumPostResponse",
    "ForumReplyCreate",
    "ForumReplyUpdate",
    "InstructorForumReplyResponse",
    "ModerationAction",
    "SentimentAnalysisResponse",
    "ForumPostQueryParams",
    "ForumReplyQueryParams",
    # Security
    "TOTPSetupResponse",
    "TOTPVerifyRequest",
    "TOTPEnableRequest",
    "TOTPDisableRequest",
    "SMSOTPEnableRequest",
    "SMSOTPVerifyRequest",
    "SMSOTPDisableRequest",
    "EmailOTPEnableRequest",
    "EmailOTPVerifyRequest",
    "EmailOTPDisableRequest",
    "TwoFactorStatusResponse",
    "BackupCodesRegenerateResponse",
    "BackupCodeVerifyRequest",
    "LoginHistoryResponse",
    "LoginHistoryQueryParams",
    "SecurityAlertResponse",
    "ActiveSessionResponse",
    "RevokeSessionRequest",
    "PasswordChangeRequest",
    "SecuritySettingsUpdate",
]
