"""instructor_dashboard_models

Revision ID: 17d3c51561bf
Revises: 010_staff_collaboration
Create Date: 2026-02-14 05:59:24.028655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17d3c51561bf'
down_revision: Union[str, None] = '010_staff_collaboration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Make every create_table / create_index idempotent so this migration can
    # run even if some tables were already created by earlier migrations.
    _conn = op.get_bind()
    _existing_tables = set(sa.inspect(_conn).get_table_names())
    _existing_indexes: set = set()
    for _t in _existing_tables:
        try:
            for _idx in sa.inspect(_conn).get_indexes(_t):
                _existing_indexes.add(_idx["name"])
        except Exception:
            pass

    _orig_create_table = op.create_table
    _orig_create_index = op.create_index

    def _safe_create_table(table_name, *args, **kwargs):
        if table_name in _existing_tables:
            return None
        return _orig_create_table(table_name, *args, **kwargs)

    def _safe_create_index(index_name, table_name, *args, **kwargs):
        if table_name in _existing_tables or index_name in _existing_indexes:
            return None
        return _orig_create_index(index_name, table_name, *args, **kwargs)

    op.create_table = _safe_create_table  # type: ignore[method-assign]
    op.create_index = _safe_create_index  # type: ignore[method-assign]

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('course_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('cbc_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_area', sa.String(length=100), nullable=False),
    sa.Column('strand', sa.String(length=100), nullable=False),
    sa.Column('sub_strand', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_cbc_competencies_area_grade', 'cbc_competencies', ['learning_area', 'grade_level'], unique=False)
    op.create_index('ix_cbc_competencies_strand', 'cbc_competencies', ['strand'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('reply_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_contact_messages_is_read'), 'contact_messages', ['is_read'], unique=False)
    op.create_table('instructor_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='badgetier'), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_badges_id'), 'instructor_badges', ['id'], unique=False)
    op.create_table('instructor_cbc_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('alignment_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('competencies_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competencies_missing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_cbc_analyses_course_id'), 'instructor_cbc_analyses', ['course_id'], unique=False)
    op.create_index(op.f('ix_instructor_cbc_analyses_created_at'), 'instructor_cbc_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_cbc_analyses_id'), 'instructor_cbc_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_cbc_analyses_instructor_id'), 'instructor_cbc_analyses', ['instructor_id'], unique=False)
    op.create_table('instructor_revenue_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('instructor_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('platform_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('partner_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('set_by', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_revenue_splits_course_id'), 'instructor_revenue_splits', ['course_id'], unique=False)
    op.create_index(op.f('ix_instructor_revenue_splits_id'), 'instructor_revenue_splits', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_revenue_splits_instructor_id'), 'instructor_revenue_splits', ['instructor_id'], unique=False)
    op.create_table('kb_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kb_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=True)
    op.create_table('system_health_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_service_checked', 'system_health_snapshots', ['service_name', 'checked_at'], unique=False)
    op.create_index('ix_health_status_checked', 'system_health_snapshots', ['status', 'checked_at'], unique=False)
    op.create_index(op.f('ix_system_health_snapshots_checked_at'), 'system_health_snapshots', ['checked_at'], unique=False)
    op.create_index(op.f('ix_system_health_snapshots_service_name'), 'system_health_snapshots', ['service_name'], unique=False)
    op.create_table('adaptive_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('learning_area', sa.String(length=100), nullable=True),
    sa.Column('cbc_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adaptive_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('is_ai_graded', sa.Boolean(), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adaptive_assessments_author_id', 'adaptive_assessments', ['author_id'], unique=False)
    op.create_index('ix_adaptive_assessments_course_id', 'adaptive_assessments', ['course_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.create_index(op.f('ix_carts_session_id'), 'carts', ['session_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_type', sa.String(length=30), nullable=False),
    sa.Column('case_ref_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_notes_type_ref', 'case_notes', ['case_type', 'case_ref_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=500), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_is_valid'), 'certificates', ['is_valid'], unique=False)
    op.create_index(op.f('ix_certificates_issued_at'), 'certificates', ['issued_at'], unique=False)
    op.create_index(op.f('ix_certificates_serial_number'), 'certificates', ['serial_number'], unique=True)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('family_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=False),
    sa.Column('primary_contact_id', sa.UUID(), nullable=False),
    sa.Column('students', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('case_status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes_count', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_family_cases_assigned_to', 'family_cases', ['assigned_to'], unique=False)
    op.create_index('ix_family_cases_case_status', 'family_cases', ['case_status'], unique=False)
    op.create_table('instructor_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('id_document_front_url', sa.String(length=500), nullable=True),
    sa.Column('id_document_back_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_applications_created_at'), 'instructor_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_applications_email'), 'instructor_applications', ['email'], unique=False)
    op.create_index(op.f('ix_instructor_applications_id'), 'instructor_applications', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_applications_status'), 'instructor_applications', ['status'], unique=False)
    op.create_index(op.f('ix_instructor_applications_user_id'), 'instructor_applications', ['user_id'], unique=False)
    op.create_table('instructor_badge_awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['instructor_badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_badge_awards_awarded_at'), 'instructor_badge_awards', ['awarded_at'], unique=False)
    op.create_index(op.f('ix_instructor_badge_awards_badge_id'), 'instructor_badge_awards', ['badge_id'], unique=False)
    op.create_index(op.f('ix_instructor_badge_awards_id'), 'instructor_badge_awards', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_badge_awards_instructor_id'), 'instructor_badge_awards', ['instructor_id'], unique=False)
    op.create_table('instructor_daily_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_daily_insights_created_at'), 'instructor_daily_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_daily_insights_id'), 'instructor_daily_insights', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_daily_insights_insight_date'), 'instructor_daily_insights', ['insight_date'], unique=False)
    op.create_index(op.f('ix_instructor_daily_insights_instructor_id'), 'instructor_daily_insights', ['instructor_id'], unique=False)
    op.create_table('instructor_earnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('earning_type', sa.Enum('COURSE_SALE', 'SESSION_FEE', 'BONUS', 'REFERRAL', name='earningtype'), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('partner_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PAID', 'REVERSED', name='earningstatus'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_earnings_course_id'), 'instructor_earnings', ['course_id'], unique=False)
    op.create_index(op.f('ix_instructor_earnings_created_at'), 'instructor_earnings', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_earnings_id'), 'instructor_earnings', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_earnings_instructor_id'), 'instructor_earnings', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_earnings_session_id'), 'instructor_earnings', ['session_id'], unique=False)
    op.create_index(op.f('ix_instructor_earnings_status'), 'instructor_earnings', ['status'], unique=False)
    op.create_table('instructor_forum_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('forum_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.Enum('DISCUSSION', 'ANNOUNCEMENT', 'QUESTION', name='posttype'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_forum_posts_created_at'), 'instructor_forum_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_forum_posts_forum_id'), 'instructor_forum_posts', ['forum_id'], unique=False)
    op.create_index(op.f('ix_instructor_forum_posts_id'), 'instructor_forum_posts', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_forum_posts_instructor_id'), 'instructor_forum_posts', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_forum_posts_post_type'), 'instructor_forum_posts', ['post_type'], unique=False)
    op.create_table('instructor_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payout_method', sa.Enum('MPESA_B2C', 'BANK_TRANSFER', 'PAYPAL', name='payoutmethod'), nullable=False),
    sa.Column('payout_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED', name='payoutstatus'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=200), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_payouts_created_at'), 'instructor_payouts', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_payouts_id'), 'instructor_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_payouts_instructor_id'), 'instructor_payouts', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_payouts_status'), 'instructor_payouts', ['status'], unique=False)
    op.create_table('instructor_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_points_id'), 'instructor_points', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_points_instructor_id'), 'instructor_points', ['instructor_id'], unique=True)
    op.create_index(op.f('ix_instructor_points_points'), 'instructor_points', ['points'], unique=False)
    op.create_table('instructor_points_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_points_logs_created_at'), 'instructor_points_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_points_logs_id'), 'instructor_points_logs', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_points_logs_instructor_id'), 'instructor_points_logs', ['instructor_id'], unique=False)
    op.create_table('instructor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaching_style', sa.String(length=100), nullable=True),
    sa.Column('ai_personality_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_profile_enabled', sa.Boolean(), nullable=True),
    sa.Column('public_slug', sa.String(length=100), nullable=True),
    sa.Column('seo_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portfolio_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_step', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_profiles_id'), 'instructor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_profiles_public_slug'), 'instructor_profiles', ['public_slug'], unique=True)
    op.create_index(op.f('ix_instructor_profiles_user_id'), 'instructor_profiles', ['user_id'], unique=True)
    op.create_table('instructor_two_factor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('totp_secret', sa.String(length=200), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_phone', sa.String(length=20), nullable=True),
    sa.Column('email_otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_two_factor_id'), 'instructor_two_factor', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_two_factor_user_id'), 'instructor_two_factor', ['user_id'], unique=True)
    op.create_table('kb_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['kb_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_kb_articles_category_id', 'kb_articles', ['category_id'], unique=False)
    op.create_index('ix_kb_articles_status', 'kb_articles', ['status'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('screen_share_enabled', sa.Boolean(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    op.create_index('ix_live_sessions_host_id', 'live_sessions', ['host_id'], unique=False)
    op.create_index('ix_live_sessions_scheduled_at', 'live_sessions', ['scheduled_at'], unique=False)
    op.create_index('ix_live_sessions_status', 'live_sessions', ['status'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('two_factor_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_created_at'), 'login_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    op.create_index(op.f('ix_login_history_success'), 'login_history', ['success'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('peer_kudos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_instructor_id', sa.UUID(), nullable=False),
    sa.Column('to_instructor_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_kudos_created_at'), 'peer_kudos', ['created_at'], unique=False)
    op.create_index(op.f('ix_peer_kudos_from_instructor_id'), 'peer_kudos', ['from_instructor_id'], unique=False)
    op.create_index(op.f('ix_peer_kudos_id'), 'peer_kudos', ['id'], unique=False)
    op.create_index(op.f('ix_peer_kudos_to_instructor_id'), 'peer_kudos', ['to_instructor_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_category_id'), 'products', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_push_subscriptions_user_id', 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('shipping_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address_line_1', sa.String(length=200), nullable=False),
    sa.Column('address_line_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_addresses_id'), 'shipping_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_shipping_addresses_user_id'), 'shipping_addresses', ['user_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('escalation_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('breach_notification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('grade_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_area', sa.String(length=100), nullable=True),
    sa.Column('cbc_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_content_items_author_id', 'staff_content_items', ['author_id'], unique=False)
    op.create_index('ix_staff_content_items_course_id', 'staff_content_items', ['course_id'], unique=False)
    op.create_index('ix_staff_content_items_status', 'staff_content_items', ['status'], unique=False)
    op.create_table('staff_moderation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('ai_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_moderation_items_assigned_to', 'staff_moderation_items', ['assigned_to'], unique=False)
    op.create_index('ix_staff_moderation_items_status', 'staff_moderation_items', ['status'], unique=False)
    op.create_table('staff_notification_prefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('digest_frequency', sa.String(length=20), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('staff_report_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_style', sa.String(length=50), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('areas_for_improvement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_journeys_risk_level', 'student_journeys', ['risk_level'], unique=False)
    op.create_index('ix_student_journeys_student_id', 'student_journeys', ['student_id'], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('cbc_competency', sa.String(length=255), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('adaptive_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_grading_prompt', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['adaptive_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_questions_assessment_id', 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_questions_difficulty', 'assessment_questions', ['difficulty'], unique=False)
    op.create_table('breakout_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('instructor_forum_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['instructor_forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_forum_replies_author_id'), 'instructor_forum_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_instructor_forum_replies_created_at'), 'instructor_forum_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_instructor_forum_replies_id'), 'instructor_forum_replies', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_forum_replies_post_id'), 'instructor_forum_replies', ['post_id'], unique=False)
    op.create_table('instructor_session_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attention_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_session_attendance_id'), 'instructor_session_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_session_attendance_session_id'), 'instructor_session_attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_instructor_session_attendance_student_id'), 'instructor_session_attendance', ['student_id'], unique=False)
    op.create_table('instructor_session_follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='followupstatus'), nullable=False),
    sa.Column('assigned_to_student_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_session_follow_ups_assigned_to_student_id'), 'instructor_session_follow_ups', ['assigned_to_student_id'], unique=False)
    op.create_index(op.f('ix_instructor_session_follow_ups_id'), 'instructor_session_follow_ups', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_session_follow_ups_instructor_id'), 'instructor_session_follow_ups', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_session_follow_ups_session_id'), 'instructor_session_follow_ups', ['session_id'], unique=False)
    op.create_index(op.f('ix_instructor_session_follow_ups_status'), 'instructor_session_follow_ups', ['status'], unique=False)
    op.create_table('kb_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_embeddings_article_id', 'kb_embeddings', ['article_id'], unique=False)
    op.create_table('live_session_recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_address_id', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['shipping_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moderation_item_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('is_ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderation_item_id'], ['staff_moderation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_decisions_moderation_item_id', 'review_decisions', ['moderation_item_id'], unique=False)
    op.create_table('staff_collab_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('yjs_doc_id', sa.String(length=100), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['staff_content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yjs_doc_id')
    )
    op.create_table('staff_content_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('body_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['staff_content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_content_versions_content_id', 'staff_content_versions', ['content_id'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('view_mode', sa.String(length=30), nullable=False),
    sa.Column('custom_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('is_department_lead', sa.Boolean(), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['staff_teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_staff_profiles_department', 'staff_profiles', ['department'], unique=False)
    op.create_index('ix_staff_profiles_team_id', 'staff_profiles', ['team_id'], unique=False)
    op.create_index('ix_staff_profiles_user_id', 'staff_profiles', ['user_id'], unique=False)
    op.create_table('staff_report_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['staff_report_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('escalated_to', sa.UUID(), nullable=True),
    sa.Column('sla_policy_id', sa.UUID(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('csat_score', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('ix_staff_tickets_assigned_to', 'staff_tickets', ['assigned_to'], unique=False)
    op.create_index('ix_staff_tickets_created_at', 'staff_tickets', ['created_at'], unique=False)
    op.create_index('ix_staff_tickets_priority_status', 'staff_tickets', ['priority', 'status'], unique=False)
    op.create_index('ix_staff_tickets_sla_deadline_active', 'staff_tickets', ['sla_deadline'], unique=False, postgresql_where=sa.text('sla_breached = false'))
    op.create_index('ix_staff_tickets_status', 'staff_tickets', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('sla_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('escalated_to', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['staff_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sla_escalations_ticket_id', 'sla_escalations', ['ticket_id'], unique=False)
    op.create_table('staff_ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['staff_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_ticket_messages_ticket_id', 'staff_ticket_messages', ['ticket_id'], unique=False)
    op.add_column('courses', sa.Column('revenue_split_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('cbc_analysis_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('ai_generated_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'courses', 'instructor_cbc_analyses', ['cbc_analysis_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'courses', 'instructor_revenue_splits', ['revenue_split_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'ai_generated_meta')
    op.drop_column('courses', 'cbc_analysis_id')
    op.drop_column('courses', 'revenue_split_id')
    op.drop_index('ix_staff_ticket_messages_ticket_id', table_name='staff_ticket_messages')
    op.drop_table('staff_ticket_messages')
    op.drop_index('ix_sla_escalations_ticket_id', table_name='sla_escalations')
    op.drop_table('sla_escalations')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_staff_tickets_status', table_name='staff_tickets')
    op.drop_index('ix_staff_tickets_sla_deadline_active', table_name='staff_tickets', postgresql_where=sa.text('sla_breached = false'))
    op.drop_index('ix_staff_tickets_priority_status', table_name='staff_tickets')
    op.drop_index('ix_staff_tickets_created_at', table_name='staff_tickets')
    op.drop_index('ix_staff_tickets_assigned_to', table_name='staff_tickets')
    op.drop_table('staff_tickets')
    op.drop_table('staff_report_schedules')
    op.drop_index('ix_staff_profiles_user_id', table_name='staff_profiles')
    op.drop_index('ix_staff_profiles_team_id', table_name='staff_profiles')
    op.drop_index('ix_staff_profiles_department', table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index('ix_staff_content_versions_content_id', table_name='staff_content_versions')
    op.drop_table('staff_content_versions')
    op.drop_table('staff_collab_sessions')
    op.drop_index('ix_review_decisions_moderation_item_id', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('live_session_recordings')
    op.drop_index('ix_kb_embeddings_article_id', table_name='kb_embeddings')
    op.drop_table('kb_embeddings')
    op.drop_index(op.f('ix_instructor_session_follow_ups_status'), table_name='instructor_session_follow_ups')
    op.drop_index(op.f('ix_instructor_session_follow_ups_session_id'), table_name='instructor_session_follow_ups')
    op.drop_index(op.f('ix_instructor_session_follow_ups_instructor_id'), table_name='instructor_session_follow_ups')
    op.drop_index(op.f('ix_instructor_session_follow_ups_id'), table_name='instructor_session_follow_ups')
    op.drop_index(op.f('ix_instructor_session_follow_ups_assigned_to_student_id'), table_name='instructor_session_follow_ups')
    op.drop_table('instructor_session_follow_ups')
    op.drop_index(op.f('ix_instructor_session_attendance_student_id'), table_name='instructor_session_attendance')
    op.drop_index(op.f('ix_instructor_session_attendance_session_id'), table_name='instructor_session_attendance')
    op.drop_index(op.f('ix_instructor_session_attendance_id'), table_name='instructor_session_attendance')
    op.drop_table('instructor_session_attendance')
    op.drop_index(op.f('ix_instructor_forum_replies_post_id'), table_name='instructor_forum_replies')
    op.drop_index(op.f('ix_instructor_forum_replies_id'), table_name='instructor_forum_replies')
    op.drop_index(op.f('ix_instructor_forum_replies_created_at'), table_name='instructor_forum_replies')
    op.drop_index(op.f('ix_instructor_forum_replies_author_id'), table_name='instructor_forum_replies')
    op.drop_table('instructor_forum_replies')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_table('breakout_rooms')
    op.drop_index('ix_assessment_questions_difficulty', table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_assessment_id', table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_index('ix_student_journeys_student_id', table_name='student_journeys')
    op.drop_index('ix_student_journeys_risk_level', table_name='student_journeys')
    op.drop_table('student_journeys')
    op.drop_table('staff_teams')
    op.drop_table('staff_report_definitions')
    op.drop_table('staff_notification_prefs')
    op.drop_index('ix_staff_moderation_items_status', table_name='staff_moderation_items')
    op.drop_index('ix_staff_moderation_items_assigned_to', table_name='staff_moderation_items')
    op.drop_table('staff_moderation_items')
    op.drop_index('ix_staff_content_items_status', table_name='staff_content_items')
    op.drop_index('ix_staff_content_items_course_id', table_name='staff_content_items')
    op.drop_index('ix_staff_content_items_author_id', table_name='staff_content_items')
    op.drop_table('staff_content_items')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_shipping_addresses_user_id'), table_name='shipping_addresses')
    op.drop_index(op.f('ix_shipping_addresses_id'), table_name='shipping_addresses')
    op.drop_table('shipping_addresses')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_push_subscriptions_user_id', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_product_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_peer_kudos_to_instructor_id'), table_name='peer_kudos')
    op.drop_index(op.f('ix_peer_kudos_id'), table_name='peer_kudos')
    op.drop_index(op.f('ix_peer_kudos_from_instructor_id'), table_name='peer_kudos')
    op.drop_index(op.f('ix_peer_kudos_created_at'), table_name='peer_kudos')
    op.drop_table('peer_kudos')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_success'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_created_at'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index('ix_live_sessions_status', table_name='live_sessions')
    op.drop_index('ix_live_sessions_scheduled_at', table_name='live_sessions')
    op.drop_index('ix_live_sessions_host_id', table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index('ix_kb_articles_status', table_name='kb_articles')
    op.drop_index('ix_kb_articles_category_id', table_name='kb_articles')
    op.drop_table('kb_articles')
    op.drop_index(op.f('ix_instructor_two_factor_user_id'), table_name='instructor_two_factor')
    op.drop_index(op.f('ix_instructor_two_factor_id'), table_name='instructor_two_factor')
    op.drop_table('instructor_two_factor')
    op.drop_index(op.f('ix_instructor_profiles_user_id'), table_name='instructor_profiles')
    op.drop_index(op.f('ix_instructor_profiles_public_slug'), table_name='instructor_profiles')
    op.drop_index(op.f('ix_instructor_profiles_id'), table_name='instructor_profiles')
    op.drop_table('instructor_profiles')
    op.drop_index(op.f('ix_instructor_points_logs_instructor_id'), table_name='instructor_points_logs')
    op.drop_index(op.f('ix_instructor_points_logs_id'), table_name='instructor_points_logs')
    op.drop_index(op.f('ix_instructor_points_logs_created_at'), table_name='instructor_points_logs')
    op.drop_table('instructor_points_logs')
    op.drop_index(op.f('ix_instructor_points_points'), table_name='instructor_points')
    op.drop_index(op.f('ix_instructor_points_instructor_id'), table_name='instructor_points')
    op.drop_index(op.f('ix_instructor_points_id'), table_name='instructor_points')
    op.drop_table('instructor_points')
    op.drop_index(op.f('ix_instructor_payouts_status'), table_name='instructor_payouts')
    op.drop_index(op.f('ix_instructor_payouts_instructor_id'), table_name='instructor_payouts')
    op.drop_index(op.f('ix_instructor_payouts_id'), table_name='instructor_payouts')
    op.drop_index(op.f('ix_instructor_payouts_created_at'), table_name='instructor_payouts')
    op.drop_table('instructor_payouts')
    op.drop_index(op.f('ix_instructor_forum_posts_post_type'), table_name='instructor_forum_posts')
    op.drop_index(op.f('ix_instructor_forum_posts_instructor_id'), table_name='instructor_forum_posts')
    op.drop_index(op.f('ix_instructor_forum_posts_id'), table_name='instructor_forum_posts')
    op.drop_index(op.f('ix_instructor_forum_posts_forum_id'), table_name='instructor_forum_posts')
    op.drop_index(op.f('ix_instructor_forum_posts_created_at'), table_name='instructor_forum_posts')
    op.drop_table('instructor_forum_posts')
    op.drop_index(op.f('ix_instructor_earnings_status'), table_name='instructor_earnings')
    op.drop_index(op.f('ix_instructor_earnings_session_id'), table_name='instructor_earnings')
    op.drop_index(op.f('ix_instructor_earnings_instructor_id'), table_name='instructor_earnings')
    op.drop_index(op.f('ix_instructor_earnings_id'), table_name='instructor_earnings')
    op.drop_index(op.f('ix_instructor_earnings_created_at'), table_name='instructor_earnings')
    op.drop_index(op.f('ix_instructor_earnings_course_id'), table_name='instructor_earnings')
    op.drop_table('instructor_earnings')
    op.drop_index(op.f('ix_instructor_daily_insights_instructor_id'), table_name='instructor_daily_insights')
    op.drop_index(op.f('ix_instructor_daily_insights_insight_date'), table_name='instructor_daily_insights')
    op.drop_index(op.f('ix_instructor_daily_insights_id'), table_name='instructor_daily_insights')
    op.drop_index(op.f('ix_instructor_daily_insights_created_at'), table_name='instructor_daily_insights')
    op.drop_table('instructor_daily_insights')
    op.drop_index(op.f('ix_instructor_badge_awards_instructor_id'), table_name='instructor_badge_awards')
    op.drop_index(op.f('ix_instructor_badge_awards_id'), table_name='instructor_badge_awards')
    op.drop_index(op.f('ix_instructor_badge_awards_badge_id'), table_name='instructor_badge_awards')
    op.drop_index(op.f('ix_instructor_badge_awards_awarded_at'), table_name='instructor_badge_awards')
    op.drop_table('instructor_badge_awards')
    op.drop_index(op.f('ix_instructor_applications_user_id'), table_name='instructor_applications')
    op.drop_index(op.f('ix_instructor_applications_status'), table_name='instructor_applications')
    op.drop_index(op.f('ix_instructor_applications_id'), table_name='instructor_applications')
    op.drop_index(op.f('ix_instructor_applications_email'), table_name='instructor_applications')
    op.drop_index(op.f('ix_instructor_applications_created_at'), table_name='instructor_applications')
    op.drop_table('instructor_applications')
    op.drop_index('ix_family_cases_case_status', table_name='family_cases')
    op.drop_index('ix_family_cases_assigned_to', table_name='family_cases')
    op.drop_table('family_cases')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_serial_number'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_issued_at'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_is_valid'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_case_notes_type_ref', table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_session_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_adaptive_assessments_course_id', table_name='adaptive_assessments')
    op.drop_index('ix_adaptive_assessments_author_id', table_name='adaptive_assessments')
    op.drop_table('adaptive_assessments')
    op.drop_index(op.f('ix_system_health_snapshots_service_name'), table_name='system_health_snapshots')
    op.drop_index(op.f('ix_system_health_snapshots_checked_at'), table_name='system_health_snapshots')
    op.drop_index('ix_health_status_checked', table_name='system_health_snapshots')
    op.drop_index('ix_health_service_checked', table_name='system_health_snapshots')
    op.drop_table('system_health_snapshots')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('kb_categories')
    op.drop_index(op.f('ix_instructor_revenue_splits_instructor_id'), table_name='instructor_revenue_splits')
    op.drop_index(op.f('ix_instructor_revenue_splits_id'), table_name='instructor_revenue_splits')
    op.drop_index(op.f('ix_instructor_revenue_splits_course_id'), table_name='instructor_revenue_splits')
    op.drop_table('instructor_revenue_splits')
    op.drop_index(op.f('ix_instructor_cbc_analyses_instructor_id'), table_name='instructor_cbc_analyses')
    op.drop_index(op.f('ix_instructor_cbc_analyses_id'), table_name='instructor_cbc_analyses')
    op.drop_index(op.f('ix_instructor_cbc_analyses_created_at'), table_name='instructor_cbc_analyses')
    op.drop_index(op.f('ix_instructor_cbc_analyses_course_id'), table_name='instructor_cbc_analyses')
    op.drop_table('instructor_cbc_analyses')
    op.drop_index(op.f('ix_instructor_badges_id'), table_name='instructor_badges')
    op.drop_table('instructor_badges')
    op.drop_index(op.f('ix_contact_messages_is_read'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index('ix_cbc_competencies_strand', table_name='cbc_competencies')
    op.drop_index('ix_cbc_competencies_area_grade', table_name='cbc_competencies')
    op.drop_table('cbc_competencies')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
