"""add copilot session and message tables

Revision ID: 8a68867dba8c
Revises: ec100aed5306
Create Date: 2026-02-18 03:53:11.400812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a68867dba8c'
down_revision: Union[str, None] = 'ec100aed5306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Make every create_table / create_index idempotent so this migration can
    # run even if some tables were already created by earlier migrations.
    _conn = op.get_bind()
    _existing_tables = set(sa.inspect(_conn).get_table_names())
    _existing_indexes: set = set()
    for _t in _existing_tables:
        try:
            for _idx in sa.inspect(_conn).get_indexes(_t):
                _existing_indexes.add(_idx["name"])
        except Exception:
            pass

    _orig_create_table = op.create_table
    _orig_create_index = op.create_index

    def _safe_create_table(table_name, *args, **kwargs):
        if table_name in _existing_tables:
            return None
        return _orig_create_table(table_name, *args, **kwargs)

    def _safe_create_index(index_name, table_name, *args, **kwargs):
        if table_name in _existing_tables or index_name in _existing_indexes:
            return None
        return _orig_create_index(index_name, table_name, *args, **kwargs)

    op.create_table = _safe_create_table  # type: ignore[method-assign]
    op.create_index = _safe_create_index  # type: ignore[method-assign]

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_performance_metrics_metric_type'), 'ai_performance_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_ai_performance_metrics_model_name'), 'ai_performance_metrics', ['model_name'], unique=False)
    op.create_index('ix_aipm_model_type', 'ai_performance_metrics', ['model_name', 'metric_type'], unique=False)
    op.create_index('ix_aipm_period', 'ai_performance_metrics', ['period_start', 'period_end'], unique=False)
    op.create_table('competency_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strand', sa.String(length=100), nullable=False),
    sa.Column('sub_strand', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_tags_grade_level'), 'competency_tags', ['grade_level'], unique=False)
    op.create_index(op.f('ix_competency_tags_name'), 'competency_tags', ['name'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('ai_diagnosed_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_endpoint_created', 'error_logs', ['endpoint', 'created_at'], unique=False)
    op.create_index('ix_error_level_created', 'error_logs', ['level', 'created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_endpoint'), 'error_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_is_resolved'), 'error_logs', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_error_logs_level'), 'error_logs', ['level'], unique=False)
    op.create_index(op.f('ix_error_logs_source'), 'error_logs', ['source'], unique=False)
    op.create_index(op.f('ix_error_logs_user_id'), 'error_logs', ['user_id'], unique=False)
    op.create_index('ix_error_resolved_created', 'error_logs', ['is_resolved', 'created_at'], unique=False)
    op.create_index('ix_error_source_created', 'error_logs', ['source', 'created_at'], unique=False)
    op.create_index('ix_error_type_created', 'error_logs', ['error_type', 'created_at'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_run_type'), 'test_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_test_runs_started_at'), 'test_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_index(op.f('ix_test_runs_triggered_by'), 'test_runs', ['triggered_by'], unique=False)
    op.create_index('ix_testrun_status_started', 'test_runs', ['status', 'started_at'], unique=False)
    op.create_index('ix_testrun_type_started', 'test_runs', ['run_type', 'started_at'], unique=False)
    op.create_table('ai_agent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('expertise_focus', sa.JSON(), nullable=True),
    sa.Column('response_style', sa.Enum('concise', 'detailed', 'conversational', 'academic', name='responsestyle'), nullable=True),
    sa.Column('quick_action_shortcuts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_profiles_user_id'), 'ai_agent_profiles', ['user_id'], unique=True)
    op.create_table('ai_content_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('flagged_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_content_reviews_content_type'), 'ai_content_reviews', ['content_type'], unique=False)
    op.create_index(op.f('ix_ai_content_reviews_status'), 'ai_content_reviews', ['status'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_is_active'), 'api_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('certificate_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_users_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_incidents_incident_type'), 'compliance_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_compliance_incidents_severity'), 'compliance_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_compliance_incidents_status'), 'compliance_incidents', ['status'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_course_id'), 'content_versions', ['course_id'], unique=False)
    op.create_index('ix_cv_course_version', 'content_versions', ['course_id', 'version_number'], unique=False)
    op.create_table('copilot_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('response_mode', sa.String(length=20), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_sessions_created_at'), 'copilot_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_sessions_id'), 'copilot_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_sessions_is_deleted'), 'copilot_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_copilot_sessions_user_id'), 'copilot_sessions', ['user_id'], unique=False)
    op.create_index('ix_copilot_sessions_user_updated', 'copilot_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_table('course_competency_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('competency_tag_id', sa.UUID(), nullable=False),
    sa.Column('coverage_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competency_tag_id'], ['competency_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ccm_course_comp', 'course_competency_mappings', ['course_id', 'competency_tag_id'], unique=True)
    op.create_index(op.f('ix_course_competency_mappings_competency_tag_id'), 'course_competency_mappings', ['competency_tag_id'], unique=False)
    op.create_index(op.f('ix_course_competency_mappings_course_id'), 'course_competency_mappings', ['course_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_partner_id'), 'invoices', ['partner_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('keyword_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_filters_category'), 'keyword_filters', ['category'], unique=False)
    op.create_index(op.f('ix_keyword_filters_keyword'), 'keyword_filters', ['keyword'], unique=False)
    op.create_table('moderation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('flag_reason', sa.String(length=100), nullable=False),
    sa.Column('flagged_by', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mod_status_severity', 'moderation_items', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_moderation_items_content_type'), 'moderation_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_moderation_items_severity'), 'moderation_items', ['severity'], unique=False)
    op.create_index(op.f('ix_moderation_items_status'), 'moderation_items', ['status'], unique=False)
    op.create_table('partner_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_contracts_partner_id'), 'partner_contracts', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_contracts_status'), 'partner_contracts', ['status'], unique=False)
    op.create_index('ix_pc_partner_status', 'partner_contracts', ['partner_id', 'status'], unique=False)
    op.create_table('payout_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_queue_recipient_id'), 'payout_queue', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_payout_queue_status'), 'payout_queue', ['status'], unique=False)
    op.create_table('resource_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_items_category'), 'resource_items', ['category'], unique=False)
    op.create_index(op.f('ix_resource_items_moderation_status'), 'resource_items', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_resource_items_title'), 'resource_items', ['title'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_category'), 'support_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_reporter_id'), 'support_tickets', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    op.create_index('ix_ticket_reporter', 'support_tickets', ['reporter_id', 'created_at'], unique=False)
    op.create_index('ix_ticket_status_priority', 'support_tickets', ['status', 'priority'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_category'), 'system_configs', ['category'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('user_restrictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('restriction_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('affected_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('appealed', sa.Boolean(), nullable=False),
    sa.Column('appeal_text', sa.Text(), nullable=True),
    sa.Column('appeal_decision', sa.String(length=20), nullable=True),
    sa.Column('appeal_decided_by', sa.UUID(), nullable=True),
    sa.Column('appeal_decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appeal_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_restriction_type_active', 'user_restrictions', ['restriction_type', 'is_active'], unique=False)
    op.create_index('ix_restriction_user_active', 'user_restrictions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_restrictions_is_active'), 'user_restrictions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_restrictions_restriction_type'), 'user_restrictions', ['restriction_type'], unique=False)
    op.create_index(op.f('ix_user_restrictions_user_id'), 'user_restrictions', ['user_id'], unique=False)
    op.create_table('ai_conversation_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_flags_conversation_id'), 'ai_conversation_flags', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_flags_flag_type'), 'ai_conversation_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_ai_conversation_flags_severity'), 'ai_conversation_flags', ['severity'], unique=False)
    op.create_index(op.f('ix_ai_conversation_flags_status'), 'ai_conversation_flags', ['status'], unique=False)
    op.create_index(op.f('ix_ai_conversation_flags_student_id'), 'ai_conversation_flags', ['student_id'], unique=False)
    op.create_index('ix_aicf_status_created', 'ai_conversation_flags', ['status', 'created_at'], unique=False)
    op.create_index('ix_aicf_type_severity', 'ai_conversation_flags', ['flag_type', 'severity'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('provider_used', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['copilot_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_messages_id'), 'copilot_messages', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_session_id'), 'copilot_messages', ['session_id'], unique=False)
    op.create_table('grade_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('original_score', sa.Float(), nullable=False),
    sa.Column('override_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_overrides_assessment_id'), 'grade_overrides', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_grade_overrides_status'), 'grade_overrides', ['status'], unique=False)
    op.create_index(op.f('ix_grade_overrides_student_id'), 'grade_overrides', ['student_id'], unique=False)
    op.create_table('system_config_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('requested_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['system_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_change_requests_config_id'), 'system_config_change_requests', ['config_id'], unique=False)
    op.create_index(op.f('ix_system_config_change_requests_status'), 'system_config_change_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_config_change_requests_status'), table_name='system_config_change_requests')
    op.drop_index(op.f('ix_system_config_change_requests_config_id'), table_name='system_config_change_requests')
    op.drop_table('system_config_change_requests')
    op.drop_index(op.f('ix_grade_overrides_student_id'), table_name='grade_overrides')
    op.drop_index(op.f('ix_grade_overrides_status'), table_name='grade_overrides')
    op.drop_index(op.f('ix_grade_overrides_assessment_id'), table_name='grade_overrides')
    op.drop_table('grade_overrides')
    op.drop_index(op.f('ix_copilot_messages_session_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_created_at'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index('ix_aicf_type_severity', table_name='ai_conversation_flags')
    op.drop_index('ix_aicf_status_created', table_name='ai_conversation_flags')
    op.drop_index(op.f('ix_ai_conversation_flags_student_id'), table_name='ai_conversation_flags')
    op.drop_index(op.f('ix_ai_conversation_flags_status'), table_name='ai_conversation_flags')
    op.drop_index(op.f('ix_ai_conversation_flags_severity'), table_name='ai_conversation_flags')
    op.drop_index(op.f('ix_ai_conversation_flags_flag_type'), table_name='ai_conversation_flags')
    op.drop_index(op.f('ix_ai_conversation_flags_conversation_id'), table_name='ai_conversation_flags')
    op.drop_table('ai_conversation_flags')
    op.drop_index(op.f('ix_user_restrictions_user_id'), table_name='user_restrictions')
    op.drop_index(op.f('ix_user_restrictions_restriction_type'), table_name='user_restrictions')
    op.drop_index(op.f('ix_user_restrictions_is_active'), table_name='user_restrictions')
    op.drop_index('ix_restriction_user_active', table_name='user_restrictions')
    op.drop_index('ix_restriction_type_active', table_name='user_restrictions')
    op.drop_table('user_restrictions')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_category'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index('ix_ticket_status_priority', table_name='support_tickets')
    op.drop_index('ix_ticket_reporter', table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_reporter_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_category'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_resource_items_title'), table_name='resource_items')
    op.drop_index(op.f('ix_resource_items_moderation_status'), table_name='resource_items')
    op.drop_index(op.f('ix_resource_items_category'), table_name='resource_items')
    op.drop_table('resource_items')
    op.drop_index(op.f('ix_payout_queue_status'), table_name='payout_queue')
    op.drop_index(op.f('ix_payout_queue_recipient_id'), table_name='payout_queue')
    op.drop_table('payout_queue')
    op.drop_index('ix_pc_partner_status', table_name='partner_contracts')
    op.drop_index(op.f('ix_partner_contracts_status'), table_name='partner_contracts')
    op.drop_index(op.f('ix_partner_contracts_partner_id'), table_name='partner_contracts')
    op.drop_table('partner_contracts')
    op.drop_index(op.f('ix_moderation_items_status'), table_name='moderation_items')
    op.drop_index(op.f('ix_moderation_items_severity'), table_name='moderation_items')
    op.drop_index(op.f('ix_moderation_items_content_type'), table_name='moderation_items')
    op.drop_index('ix_mod_status_severity', table_name='moderation_items')
    op.drop_table('moderation_items')
    op.drop_index(op.f('ix_keyword_filters_keyword'), table_name='keyword_filters')
    op.drop_index(op.f('ix_keyword_filters_category'), table_name='keyword_filters')
    op.drop_table('keyword_filters')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_partner_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_course_competency_mappings_course_id'), table_name='course_competency_mappings')
    op.drop_index(op.f('ix_course_competency_mappings_competency_tag_id'), table_name='course_competency_mappings')
    op.drop_index('ix_ccm_course_comp', table_name='course_competency_mappings')
    op.drop_table('course_competency_mappings')
    op.drop_index('ix_copilot_sessions_user_updated', table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_user_id'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_is_deleted'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_id'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_created_at'), table_name='copilot_sessions')
    op.drop_table('copilot_sessions')
    op.drop_index('ix_cv_course_version', table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_course_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_compliance_incidents_status'), table_name='compliance_incidents')
    op.drop_index(op.f('ix_compliance_incidents_severity'), table_name='compliance_incidents')
    op.drop_index(op.f('ix_compliance_incidents_incident_type'), table_name='compliance_incidents')
    op.drop_table('compliance_incidents')
    op.drop_table('certificate_templates')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_is_active'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_ai_content_reviews_status'), table_name='ai_content_reviews')
    op.drop_index(op.f('ix_ai_content_reviews_content_type'), table_name='ai_content_reviews')
    op.drop_table('ai_content_reviews')
    op.drop_index(op.f('ix_ai_agent_profiles_user_id'), table_name='ai_agent_profiles')
    op.drop_table('ai_agent_profiles')
    op.drop_index('ix_testrun_type_started', table_name='test_runs')
    op.drop_index('ix_testrun_status_started', table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_triggered_by'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_started_at'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_run_type'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index('ix_error_type_created', table_name='error_logs')
    op.drop_index('ix_error_source_created', table_name='error_logs')
    op.drop_index('ix_error_resolved_created', table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_user_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_source'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_level'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_is_resolved'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_endpoint'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index('ix_error_level_created', table_name='error_logs')
    op.drop_index('ix_error_endpoint_created', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_competency_tags_name'), table_name='competency_tags')
    op.drop_index(op.f('ix_competency_tags_grade_level'), table_name='competency_tags')
    op.drop_table('competency_tags')
    op.drop_index('ix_aipm_period', table_name='ai_performance_metrics')
    op.drop_index('ix_aipm_model_type', table_name='ai_performance_metrics')
    op.drop_index(op.f('ix_ai_performance_metrics_model_name'), table_name='ai_performance_metrics')
    op.drop_index(op.f('ix_ai_performance_metrics_metric_type'), table_name='ai_performance_metrics')
    op.drop_table('ai_performance_metrics')
    # ### end Alembic commands ###
