"""Add parent dashboard models and 2FA security

Revision ID: d5d1ae80ad6c
Revises: 17d3c51561bf
Create Date: 2026-02-14 12:39:23.110104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5d1ae80ad6c'
down_revision: Union[str, None] = '17d3c51561bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='meetingstatus'), nullable=False),
    sa.Column('ai_suggested', sa.Boolean(), nullable=True),
    sa.Column('ai_agenda', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_meetings_created_at'), 'partner_meetings', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_meetings_id'), 'partner_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_partner_meetings_partner_id'), 'partner_meetings', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_meetings_status'), 'partner_meetings', ['status'], unique=False)
    op.create_table('partner_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['partner_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_messages_created_at'), 'partner_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_messages_id'), 'partner_messages', ['id'], unique=False)
    op.create_index(op.f('ix_partner_messages_partner_id'), 'partner_messages', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_messages_recipient_id'), 'partner_messages', ['recipient_id'], unique=False)
    op.create_table('partner_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=300), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('tax_exempt', sa.Boolean(), nullable=True),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partnership_tier', sa.String(length=50), nullable=True),
    sa.Column('branding_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_step', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_profiles_id'), 'partner_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_partner_profiles_user_id'), 'partner_profiles', ['user_id'], unique=True)
    op.create_table('partner_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.Enum('LESSON', 'MATERIAL', 'VIDEO', 'DOCUMENT', 'WORKSHEET', 'ASSESSMENT', name='resourcetype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='resourcestatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('branding_applied', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('target_programs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_grade_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_resources_created_at'), 'partner_resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_resources_id'), 'partner_resources', ['id'], unique=False)
    op.create_index(op.f('ix_partner_resources_partner_id'), 'partner_resources', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_resources_status'), 'partner_resources', ['status'], unique=False)
    op.create_table('sponsorship_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('program_type', sa.Enum('DIRECT', 'COHORT', name='programtype'), nullable=False),
    sa.Column('min_children', sa.Integer(), nullable=False),
    sa.Column('max_children', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='programstatus'), nullable=False),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'TERMLY', 'ANNUAL', name='billingperiod'), nullable=True),
    sa.Column('price_per_child', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('custom_pricing_notes', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_grade_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_programs_created_at'), 'sponsorship_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsorship_programs_id'), 'sponsorship_programs', ['id'], unique=False)
    op.create_index(op.f('ix_sponsorship_programs_partner_id'), 'sponsorship_programs', ['partner_id'], unique=False)
    op.create_index('ix_sponsorship_programs_partner_status', 'sponsorship_programs', ['partner_id', 'status'], unique=False)
    op.create_index(op.f('ix_sponsorship_programs_status'), 'sponsorship_programs', ['status'], unique=False)
    op.create_table('user_login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_history_id'), 'user_login_history', ['id'], unique=False)
    op.create_index(op.f('ix_user_login_history_login_at'), 'user_login_history', ['login_at'], unique=False)
    op.create_index(op.f('ix_user_login_history_success'), 'user_login_history', ['success'], unique=False)
    op.create_index(op.f('ix_user_login_history_user_id'), 'user_login_history', ['user_id'], unique=False)
    op.create_table('user_two_factor_auth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_phone', sa.String(length=20), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recovery_email', sa.String(length=255), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_two_factor_auth_id'), 'user_two_factor_auth', ['id'], unique=False)
    op.create_index(op.f('ix_user_two_factor_auth_user_id'), 'user_two_factor_auth', ['user_id'], unique=True)
    op.create_table('parent_ai_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_ai_alerts_alert_type'), 'parent_ai_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_parent_ai_alerts_child_id'), 'parent_ai_alerts', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_ai_alerts_created_at'), 'parent_ai_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_parent_ai_alerts_id'), 'parent_ai_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_parent_ai_alerts_is_read'), 'parent_ai_alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_parent_ai_alerts_parent_id'), 'parent_ai_alerts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_ai_alerts_severity'), 'parent_ai_alerts', ['severity'], unique=False)
    op.create_table('parent_consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('recipient_type', sa.String(length=100), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_consent_records_child_id'), 'parent_consent_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_consent_records_consent_given'), 'parent_consent_records', ['consent_given'], unique=False)
    op.create_index(op.f('ix_parent_consent_records_data_type'), 'parent_consent_records', ['data_type'], unique=False)
    op.create_index(op.f('ix_parent_consent_records_id'), 'parent_consent_records', ['id'], unique=False)
    op.create_index(op.f('ix_parent_consent_records_parent_id'), 'parent_consent_records', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_consent_records_recipient_type'), 'parent_consent_records', ['recipient_type'], unique=False)
    op.create_table('parent_family_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_family_goals_child_id'), 'parent_family_goals', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_family_goals_created_at'), 'parent_family_goals', ['created_at'], unique=False)
    op.create_index(op.f('ix_parent_family_goals_id'), 'parent_family_goals', ['id'], unique=False)
    op.create_index(op.f('ix_parent_family_goals_parent_id'), 'parent_family_goals', ['parent_id'], unique=False)
    op.create_table('parent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_messages_channel'), 'parent_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_parent_messages_child_id'), 'parent_messages', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_conversation_id'), 'parent_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_created_at'), 'parent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_parent_messages_id'), 'parent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_parent_messages_is_read'), 'parent_messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_parent_messages_recipient_id'), 'parent_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_parent_messages_sender_id'), 'parent_messages', ['sender_id'], unique=False)
    op.create_table('parent_mood_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_mood_entries_child_id'), 'parent_mood_entries', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_mood_entries_id'), 'parent_mood_entries', ['id'], unique=False)
    op.create_index(op.f('ix_parent_mood_entries_parent_id'), 'parent_mood_entries', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_mood_entries_recorded_date'), 'parent_mood_entries', ['recorded_date'], unique=False)
    op.create_table('parent_notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel_email', sa.Boolean(), nullable=False),
    sa.Column('channel_sms', sa.Boolean(), nullable=False),
    sa.Column('channel_push', sa.Boolean(), nullable=False),
    sa.Column('channel_in_app', sa.Boolean(), nullable=False),
    sa.Column('severity_threshold', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_notification_preferences_child_id'), 'parent_notification_preferences', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_notification_preferences_id'), 'parent_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_parent_notification_preferences_is_enabled'), 'parent_notification_preferences', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_parent_notification_preferences_notification_type'), 'parent_notification_preferences', ['notification_type'], unique=False)
    op.create_index(op.f('ix_parent_notification_preferences_parent_id'), 'parent_notification_preferences', ['parent_id'], unique=False)
    op.create_table('parent_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_projections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_reports_child_id'), 'parent_reports', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_reports_created_at'), 'parent_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_parent_reports_id'), 'parent_reports', ['id'], unique=False)
    op.create_index(op.f('ix_parent_reports_parent_id'), 'parent_reports', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_reports_period_end'), 'parent_reports', ['period_end'], unique=False)
    op.create_index(op.f('ix_parent_reports_period_start'), 'parent_reports', ['period_start'], unique=False)
    op.create_index(op.f('ix_parent_reports_report_type'), 'parent_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_parent_reports_status'), 'parent_reports', ['status'], unique=False)
    op.create_table('partner_impact_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('MONTHLY', 'TERMLY', 'ANNUAL', 'CUSTOM', name='reporttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cbc_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('export_format', sa.Enum('PDF', 'CSV', 'XLSX', name='exportformat'), nullable=True),
    sa.Column('export_url', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['sponsorship_programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_impact_reports_created_at'), 'partner_impact_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_impact_reports_id'), 'partner_impact_reports', ['id'], unique=False)
    op.create_index(op.f('ix_partner_impact_reports_partner_id'), 'partner_impact_reports', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_impact_reports_program_id'), 'partner_impact_reports', ['program_id'], unique=False)
    op.create_table('partner_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('amount_per_child', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_children', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', 'PAUSED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('payment_method_id', sa.UUID(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['sponsorship_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_subscriptions_created_at'), 'partner_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_subscriptions_id'), 'partner_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_partner_subscriptions_partner_id'), 'partner_subscriptions', ['partner_id'], unique=False)
    op.create_index('ix_partner_subscriptions_partner_status', 'partner_subscriptions', ['partner_id', 'status'], unique=False)
    op.create_index(op.f('ix_partner_subscriptions_program_id'), 'partner_subscriptions', ['program_id'], unique=False)
    op.create_index(op.f('ix_partner_subscriptions_status'), 'partner_subscriptions', ['status'], unique=False)
    op.create_table('partner_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SPONSORSHIP', 'BILLING', 'TECHNICAL', 'CONTENT', 'REPORTING', 'CONSENT', 'GENERAL', name='ticketcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_ON_PARTNER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('ai_triage_category', sa.String(length=100), nullable=True),
    sa.Column('ai_triage_priority', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['sponsorship_programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_tickets_assigned_status', 'partner_tickets', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_partner_tickets_assigned_to'), 'partner_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_partner_tickets_created_at'), 'partner_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_tickets_id'), 'partner_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_partner_tickets_partner_id'), 'partner_tickets', ['partner_id'], unique=False)
    op.create_index('ix_partner_tickets_partner_status', 'partner_tickets', ['partner_id', 'status'], unique=False)
    op.create_index(op.f('ix_partner_tickets_status'), 'partner_tickets', ['status'], unique=False)
    op.create_table('sponsored_children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_CONSENT', 'ACTIVE', 'PAUSED', 'GRADUATED', 'REMOVED', name='sponsoredchildstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('partner_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['sponsorship_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'student_id', name='uq_program_student')
    )
    op.create_index(op.f('ix_sponsored_children_id'), 'sponsored_children', ['id'], unique=False)
    op.create_index(op.f('ix_sponsored_children_partner_id'), 'sponsored_children', ['partner_id'], unique=False)
    op.create_index('ix_sponsored_children_partner_status', 'sponsored_children', ['partner_id', 'status'], unique=False)
    op.create_index(op.f('ix_sponsored_children_program_id'), 'sponsored_children', ['program_id'], unique=False)
    op.create_index(op.f('ix_sponsored_children_status'), 'sponsored_children', ['status'], unique=False)
    op.create_index(op.f('ix_sponsored_children_student_id'), 'sponsored_children', ['student_id'], unique=False)
    op.create_table('parent_consent_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consent_record_id', sa.UUID(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Boolean(), nullable=True),
    sa.Column('new_value', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consent_record_id'], ['parent_consent_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_consent_audit_log_consent_record_id'), 'parent_consent_audit_log', ['consent_record_id'], unique=False)
    op.create_index(op.f('ix_parent_consent_audit_log_created_at'), 'parent_consent_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_parent_consent_audit_log_id'), 'parent_consent_audit_log', ['id'], unique=False)
    op.create_table('partner_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_gateway', sa.Enum('MPESA', 'STRIPE', 'PAYPAL', name='paymentgateway'), nullable=True),
    sa.Column('transaction_reference', sa.String(length=200), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['partner_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index(op.f('ix_partner_payments_created_at'), 'partner_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_payments_id'), 'partner_payments', ['id'], unique=False)
    op.create_index(op.f('ix_partner_payments_partner_id'), 'partner_payments', ['partner_id'], unique=False)
    op.create_index('ix_partner_payments_partner_status', 'partner_payments', ['partner_id', 'status'], unique=False)
    op.create_index(op.f('ix_partner_payments_status'), 'partner_payments', ['status'], unique=False)
    op.create_index(op.f('ix_partner_payments_subscription_id'), 'partner_payments', ['subscription_id'], unique=False)
    op.create_table('sponsorship_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sponsored_child_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsored_child_id'], ['sponsored_children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorship_consents_id'), 'sponsorship_consents', ['id'], unique=False)
    op.create_index(op.f('ix_sponsorship_consents_parent_id'), 'sponsorship_consents', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_consents_sponsored_child_id'), 'sponsorship_consents', ['sponsored_child_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorship_consents_sponsored_child_id'), table_name='sponsorship_consents')
    op.drop_index(op.f('ix_sponsorship_consents_parent_id'), table_name='sponsorship_consents')
    op.drop_index(op.f('ix_sponsorship_consents_id'), table_name='sponsorship_consents')
    op.drop_table('sponsorship_consents')
    op.drop_index(op.f('ix_partner_payments_subscription_id'), table_name='partner_payments')
    op.drop_index(op.f('ix_partner_payments_status'), table_name='partner_payments')
    op.drop_index('ix_partner_payments_partner_status', table_name='partner_payments')
    op.drop_index(op.f('ix_partner_payments_partner_id'), table_name='partner_payments')
    op.drop_index(op.f('ix_partner_payments_id'), table_name='partner_payments')
    op.drop_index(op.f('ix_partner_payments_created_at'), table_name='partner_payments')
    op.drop_table('partner_payments')
    op.drop_index(op.f('ix_parent_consent_audit_log_id'), table_name='parent_consent_audit_log')
    op.drop_index(op.f('ix_parent_consent_audit_log_created_at'), table_name='parent_consent_audit_log')
    op.drop_index(op.f('ix_parent_consent_audit_log_consent_record_id'), table_name='parent_consent_audit_log')
    op.drop_table('parent_consent_audit_log')
    op.drop_index(op.f('ix_sponsored_children_student_id'), table_name='sponsored_children')
    op.drop_index(op.f('ix_sponsored_children_status'), table_name='sponsored_children')
    op.drop_index(op.f('ix_sponsored_children_program_id'), table_name='sponsored_children')
    op.drop_index('ix_sponsored_children_partner_status', table_name='sponsored_children')
    op.drop_index(op.f('ix_sponsored_children_partner_id'), table_name='sponsored_children')
    op.drop_index(op.f('ix_sponsored_children_id'), table_name='sponsored_children')
    op.drop_table('sponsored_children')
    op.drop_index(op.f('ix_partner_tickets_status'), table_name='partner_tickets')
    op.drop_index('ix_partner_tickets_partner_status', table_name='partner_tickets')
    op.drop_index(op.f('ix_partner_tickets_partner_id'), table_name='partner_tickets')
    op.drop_index(op.f('ix_partner_tickets_id'), table_name='partner_tickets')
    op.drop_index(op.f('ix_partner_tickets_created_at'), table_name='partner_tickets')
    op.drop_index(op.f('ix_partner_tickets_assigned_to'), table_name='partner_tickets')
    op.drop_index('ix_partner_tickets_assigned_status', table_name='partner_tickets')
    op.drop_table('partner_tickets')
    op.drop_index(op.f('ix_partner_subscriptions_status'), table_name='partner_subscriptions')
    op.drop_index(op.f('ix_partner_subscriptions_program_id'), table_name='partner_subscriptions')
    op.drop_index('ix_partner_subscriptions_partner_status', table_name='partner_subscriptions')
    op.drop_index(op.f('ix_partner_subscriptions_partner_id'), table_name='partner_subscriptions')
    op.drop_index(op.f('ix_partner_subscriptions_id'), table_name='partner_subscriptions')
    op.drop_index(op.f('ix_partner_subscriptions_created_at'), table_name='partner_subscriptions')
    op.drop_table('partner_subscriptions')
    op.drop_index(op.f('ix_partner_impact_reports_program_id'), table_name='partner_impact_reports')
    op.drop_index(op.f('ix_partner_impact_reports_partner_id'), table_name='partner_impact_reports')
    op.drop_index(op.f('ix_partner_impact_reports_id'), table_name='partner_impact_reports')
    op.drop_index(op.f('ix_partner_impact_reports_created_at'), table_name='partner_impact_reports')
    op.drop_table('partner_impact_reports')
    op.drop_index(op.f('ix_parent_reports_status'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_report_type'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_period_start'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_period_end'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_parent_id'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_id'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_created_at'), table_name='parent_reports')
    op.drop_index(op.f('ix_parent_reports_child_id'), table_name='parent_reports')
    op.drop_table('parent_reports')
    op.drop_index(op.f('ix_parent_notification_preferences_parent_id'), table_name='parent_notification_preferences')
    op.drop_index(op.f('ix_parent_notification_preferences_notification_type'), table_name='parent_notification_preferences')
    op.drop_index(op.f('ix_parent_notification_preferences_is_enabled'), table_name='parent_notification_preferences')
    op.drop_index(op.f('ix_parent_notification_preferences_id'), table_name='parent_notification_preferences')
    op.drop_index(op.f('ix_parent_notification_preferences_child_id'), table_name='parent_notification_preferences')
    op.drop_table('parent_notification_preferences')
    op.drop_index(op.f('ix_parent_mood_entries_recorded_date'), table_name='parent_mood_entries')
    op.drop_index(op.f('ix_parent_mood_entries_parent_id'), table_name='parent_mood_entries')
    op.drop_index(op.f('ix_parent_mood_entries_id'), table_name='parent_mood_entries')
    op.drop_index(op.f('ix_parent_mood_entries_child_id'), table_name='parent_mood_entries')
    op.drop_table('parent_mood_entries')
    op.drop_index(op.f('ix_parent_messages_sender_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_recipient_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_is_read'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_created_at'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_conversation_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_child_id'), table_name='parent_messages')
    op.drop_index(op.f('ix_parent_messages_channel'), table_name='parent_messages')
    op.drop_table('parent_messages')
    op.drop_index(op.f('ix_parent_family_goals_parent_id'), table_name='parent_family_goals')
    op.drop_index(op.f('ix_parent_family_goals_id'), table_name='parent_family_goals')
    op.drop_index(op.f('ix_parent_family_goals_created_at'), table_name='parent_family_goals')
    op.drop_index(op.f('ix_parent_family_goals_child_id'), table_name='parent_family_goals')
    op.drop_table('parent_family_goals')
    op.drop_index(op.f('ix_parent_consent_records_recipient_type'), table_name='parent_consent_records')
    op.drop_index(op.f('ix_parent_consent_records_parent_id'), table_name='parent_consent_records')
    op.drop_index(op.f('ix_parent_consent_records_id'), table_name='parent_consent_records')
    op.drop_index(op.f('ix_parent_consent_records_data_type'), table_name='parent_consent_records')
    op.drop_index(op.f('ix_parent_consent_records_consent_given'), table_name='parent_consent_records')
    op.drop_index(op.f('ix_parent_consent_records_child_id'), table_name='parent_consent_records')
    op.drop_table('parent_consent_records')
    op.drop_index(op.f('ix_parent_ai_alerts_severity'), table_name='parent_ai_alerts')
    op.drop_index(op.f('ix_parent_ai_alerts_parent_id'), table_name='parent_ai_alerts')
    op.drop_index(op.f('ix_parent_ai_alerts_is_read'), table_name='parent_ai_alerts')
    op.drop_index(op.f('ix_parent_ai_alerts_id'), table_name='parent_ai_alerts')
    op.drop_index(op.f('ix_parent_ai_alerts_created_at'), table_name='parent_ai_alerts')
    op.drop_index(op.f('ix_parent_ai_alerts_child_id'), table_name='parent_ai_alerts')
    op.drop_index(op.f('ix_parent_ai_alerts_alert_type'), table_name='parent_ai_alerts')
    op.drop_table('parent_ai_alerts')
    op.drop_index(op.f('ix_user_two_factor_auth_user_id'), table_name='user_two_factor_auth')
    op.drop_index(op.f('ix_user_two_factor_auth_id'), table_name='user_two_factor_auth')
    op.drop_table('user_two_factor_auth')
    op.drop_index(op.f('ix_user_login_history_user_id'), table_name='user_login_history')
    op.drop_index(op.f('ix_user_login_history_success'), table_name='user_login_history')
    op.drop_index(op.f('ix_user_login_history_login_at'), table_name='user_login_history')
    op.drop_index(op.f('ix_user_login_history_id'), table_name='user_login_history')
    op.drop_table('user_login_history')
    op.drop_index(op.f('ix_sponsorship_programs_status'), table_name='sponsorship_programs')
    op.drop_index('ix_sponsorship_programs_partner_status', table_name='sponsorship_programs')
    op.drop_index(op.f('ix_sponsorship_programs_partner_id'), table_name='sponsorship_programs')
    op.drop_index(op.f('ix_sponsorship_programs_id'), table_name='sponsorship_programs')
    op.drop_index(op.f('ix_sponsorship_programs_created_at'), table_name='sponsorship_programs')
    op.drop_table('sponsorship_programs')
    op.drop_index(op.f('ix_partner_resources_status'), table_name='partner_resources')
    op.drop_index(op.f('ix_partner_resources_partner_id'), table_name='partner_resources')
    op.drop_index(op.f('ix_partner_resources_id'), table_name='partner_resources')
    op.drop_index(op.f('ix_partner_resources_created_at'), table_name='partner_resources')
    op.drop_table('partner_resources')
    op.drop_index(op.f('ix_partner_profiles_user_id'), table_name='partner_profiles')
    op.drop_index(op.f('ix_partner_profiles_id'), table_name='partner_profiles')
    op.drop_table('partner_profiles')
    op.drop_index(op.f('ix_partner_messages_recipient_id'), table_name='partner_messages')
    op.drop_index(op.f('ix_partner_messages_partner_id'), table_name='partner_messages')
    op.drop_index(op.f('ix_partner_messages_id'), table_name='partner_messages')
    op.drop_index(op.f('ix_partner_messages_created_at'), table_name='partner_messages')
    op.drop_table('partner_messages')
    op.drop_index(op.f('ix_partner_meetings_status'), table_name='partner_meetings')
    op.drop_index(op.f('ix_partner_meetings_partner_id'), table_name='partner_meetings')
    op.drop_index(op.f('ix_partner_meetings_id'), table_name='partner_meetings')
    op.drop_index(op.f('ix_partner_meetings_created_at'), table_name='partner_meetings')
    op.drop_table('partner_meetings')
    # ### end Alembic commands ###
